### ISSUE TITLE
CDAP.io - home page - "Why CDAP" blurbs have an inconsistent character count 

### ISSUE THREAD

**Issue by leacd** [cdapio/website#16]
The four blurbs under the title "Why CDAP" should have a consistent character count or at least number of lines. 

Please reduce of 18 characters
**Reduced complexity**
CDAP lowers barrier to entry to complex technologies. It increases developer productivity through focus on business logic; and leads to accelerated ROI

Please reduce of 60 characters 
**Increased velocity**
CDAP platform and intuitive UI allow, rapid onboarding and faster time to production. It provides business value, by reducing repetition and silos, and promoting reuse and self service: build once, run anywhere

Please check grammar and punctuation as well.

**Comment by bdmogal** [comment]
Reduced complexity
CDAP's easy to use abstractions over complex technologies shift focus to insights from infrastructure and integration. 

Increased velocity
With an extensible framework and reusable templates, CDAP accelerates time to value and breaks down silos, so you can build once, run anywhere
