### ISSUE TITLE
Accelerators - Pipeline text needs to be edited and cut

### ISSUE THREAD

**Issue by leacd** [cdapio/website#21]
Please cut 130 characters

**Pipelines**
Pipelines is an accelerator for data integration use cases. It provides an easy-to-use graphical interface that allows you to bring together data from a myriad of different sources and define transformations visually. It lowers the barrier to data integration, and enables developers, business analysts and data scientists to quickly derive insights from data by cleansing, preparing, blending, transforming and transferring data without having to worry about infrastructure and integration.

**Comment by bdmogal** [comment]
Do we have to cut it to 130 characters, or cut 130 characters? Is the following ok?

Pipelines provides an easy-to-use graphical data integration interface to bring together data from a myriad of different sources and define transformations visually. It enables developers, business analysts and data scientists to quickly cleanse, blend, transform and transfer data without having to worry about infrastructure and integration.

**Comment by leacd** [comment]
Yes, that should works. Thanks!
