### ISSUE TITLE
Pipeline details page text - Pipeline benefits title and blurbs need to have similar characters count and line count

### ISSUE THREAD

**Issue by leacd** [cdapio/website#22]
In the Pipelines page (under Accelerators) the blurbs related to benefits need to have a similar character count so that the titles and text occupies a similar amount of space. 

Please reduce  
_**Integrated with any and all data**_
Pipelines offers a rich ecosystem of connectors for a variety of legacy systems, relational databases, file systems, cloud services, object stores, NoSQL, EBCDIC, and more.
(cut 100 characters from the text)

**Reduced complexity, increased productivity**
Pipelines has a visual interface for building data pipelines, code free transformations, and reusable pipeline blueprints.
(cut the title in half - 28 character max)

**Comment by bdmogal** [comment]
**Integrate with all data**
Pipelines provide connectors to relational databases, flat files, mainframes, cloud services, NoSQL, and more.

**Reduce complexity**
Pipelines reduce complexity through a graphical interface, code free transformations, and reusable tempates.
(cut the title in half - 28 character max)
