### ISSUE TITLE
Preparation (Wrangler) details page - need links to videos

### ISSUE THREAD

**Issue by leacd** [cdapio/website#25]
Currently, we have a video section at the bottom of the Preparation page with placeholders.  We need links to real content and video

**Comment by bdmogal** [comment]
https://www.youtube.com/watch?v=cGYmMtGO9Lo
https://www.youtube.com/watch?v=Zt_mzikca94
https://www.youtube.com/watch?v=9LHmTybkU50
https://www.youtube.com/watch?v=0ZoTvyCD4tQ
https://www.youtube.com/watch?v=y-gPtDJtiSI
https://www.youtube.com/watch?v=OBIUBMKQHGo
