### ISSUE TITLE
Plugin filters should support more types.

### ISSUE THREAD

**Issue by bdmogal** [cdapio/website#49]
All the types in the script should be supported. The supported types are in a dictionary in the beginning of the script.

**Comment by dbuzhorkaa** [comment]
@bdmogal what other types should be supported? Where I can find the complete list of supported plugins?

**Comment by bdmogal** [comment]
@dbuzhorkaa the list of plugins is in the script - https://github.com/cdapio/website/blob/develop/scripts/generate-plugins/main.py#L33-L49

**Comment by bdmogal** [comment]
Use a unique list of values from that map.
