### ISSUE TITLE
Plugins and video pages hero content are missed

### ISSUE THREAD

**Issue by dbuzhorkaa** [cdapio/website#59]

**Comment by bdmogal** [comment]
Plugins:
CDAP is highly extensible, and exposes plugins, which allow users to extend its capabilities. On this page, you can see all the plugins available in CDAP. Refer to the community page to learn about writing your own plugin.

Videos:
This page contains educational videos, tutorials as well as presentations from the BDAM meetup group. Subscribe to the CDAP channel on YouTube to get notifications about new videos.
