### ISSUE TITLE
Add a "Featured" indicator for Cloud Data Fusion

### ISSUE THREAD

**Issue by bdmogal** [cdapio/website#65]
Somehow need to make Cloud Data Fusion stand out in the Get Started page. Something like a Featured tag. @leacd any thoughts?

**Comment by leacd** [comment]
I am attaching a screen shot of the "Featured" tag. 

![image](https://user-images.githubusercontent.com/24595577/56313178-d30c2f80-6106-11e9-9980-96d0ed922dd7.png)
