### ISSUE TITLE
Plugins under resources makes no senss

### ISSUE THREAD

**Issue by nitinmotgi** [cdapio/website#76]
We should remove Plugin under resources. They should be in the context of data pipeline. It seems misplaced and gives the impression that it's for all of cdap

**Comment by dbuzhorkaa** [comment]
@nitinmotgi  @bdmogal  do we need to remove Plugins from the footer?

![image](https://user-images.githubusercontent.com/48436532/56434070-c7259680-62db-11e9-948c-698b656b8bfc.png)
