### ISSUE TITLE
Inconsistency in vocabulary used for a product

### ISSUE THREAD

**Issue by anwar6953** [cdapio/website#80]
On [this page](https://cdap-website-develop.netlify.com/accelerators/wrangler/), the verbiage used is Wrangler.
However, on [the documentation](https://docs.cdap.io/cdap/current/en/user-guide/data-preparation/index.html) linked on that page, the verbiage is Data Preparation.

This is confusing and potentially misleading.

**Comment by bdmogal** [comment]
@anwar6953 this can't really be fixed in the website. Let's create a jira and fix the documentation instead? I'll close this one.

**Comment by anwar6953** [comment]
Done: https://issues.cask.co/browse/CDAP-15278
